pipelines:
  - name: pipeline_A_TemplateSync_7299_001
    steps:
      - name: A_TemplateSync_7299_001
        type: Bash
        execution:
          onExecute:
            - echo "Running test case A_TemplateSync_7299_001"
